version: '2'
services:
  db:
    image: postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    links:
      - db
    env_file: .env.backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev

    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/code
