FROM node:6.3.1-slim

# Create app directory
RUN mkdir -p /code
WORKDIR /code

# Install app dependencies
COPY package.json /code/
RUN npm install

RUN npm i -g nodemon

EXPOSE 8080
CMD [ "nodemon", "server.js" ]
