version: '2'
services:
  db:
    image: postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    links:
      - db
    environment:
      - DATABASE_URL=postgres://db:5432
      - PORT=8000
